# Use official Nginx image
FROM nginx:alpine

# Copy the WAR file generated by Jenkins
# Assuming Jenkins builds WAR to target/*.war
# We'll extract the 'static' folder from the WAR to Nginx html
ARG WAR_FILE=target/java-maven-webpage-1.0-SNAPSHOT.war

# Install unzip inside the container to extract the WAR
RUN apk add --no-cache unzip

# Create a temporary directory and extract static content
RUN mkdir /tmp/war
COPY ${WAR_FILE} /tmp/war/app.war
RUN unzip /tmp/war/app.war -d /tmp/war/extracted
# Copy static content to Nginx html folder
RUN cp -r /tmp/war/extracted/static/* /usr/share/nginx/html/

# Clean up temporary files
RUN rm -rf /tmp/war

# Expose Nginx port
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
